-- MySQL Script generated by MySQL Workbench
-- Mon May 24 14:40:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brief-5-gestion-emploit-v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brief-5-gestion-emploit-v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brief-5-gestion-emploit-v2` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `brief-5-gestion-emploit-v2` ;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Ensegniant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Ensegniant` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Ensegniant` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `Matiere_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ensegniant_Matiere1_idx` (`Matiere_id` ASC),
  CONSTRAINT `fk_Ensegniant_Matiere1`
    FOREIGN KEY (`Matiere_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Matiere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Ensegniant_groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Ensegniant_groupe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Ensegniant_groupe` (
  `id` INT NOT NULL,
  `Ensegniant_id` INT NOT NULL,
  `Groupe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ensegniant_groupe_Ensegniant1_idx` (`Ensegniant_id` ASC),
  INDEX `fk_Ensegniant_groupe_Groupe1_idx` (`Groupe_id` ASC),
  CONSTRAINT `fk_Ensegniant_groupe_Ensegniant1`
    FOREIGN KEY (`Ensegniant_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Ensegniant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensegniant_groupe_Groupe1`
    FOREIGN KEY (`Groupe_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Groupe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Groupe` (
  `id` INT NOT NULL,
  `effecrif` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Matiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Matiere` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Matiere` (
  `id` INT NOT NULL,
  `Matiere_label` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Periode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Periode` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Periode` (
  `id` INT NOT NULL,
  `de` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Salle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Salle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Salle` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  `capacite` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Suiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Suiver` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Suiver` (
  `id` INT NOT NULL,
  `Ensegniant_id` INT NOT NULL,
  `Groupe_id` INT NOT NULL,
  `jour` INT NULL,
  `de` TIME NULL,
  `a` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Suiver_Ensegniant1_idx` (`Ensegniant_id` ASC),
  INDEX `fk_Suiver_Groupe1_idx` (`Groupe_id` ASC),
  CONSTRAINT `fk_Suiver_Ensegniant1`
    FOREIGN KEY (`Ensegniant_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Ensegniant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suiver_Groupe1`
    FOREIGN KEY (`Groupe_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`Suiver_Periode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`Suiver_Periode` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`Suiver_Periode` (
  `id` INT NOT NULL,
  `Periode_id` INT NOT NULL,
  `Suiver_id` INT NOT NULL,
  `isReserved` BINARY NULL,
  `jour` INT NULL,
  `Salle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Suiver_Persiode_Periode1_idx` (`Periode_id` ASC),
  INDEX `fk_Suiver_Persiode_Suiver1_idx` (`Suiver_id` ASC),
  INDEX `fk_Suiver_Periode_Salle1_idx` (`Salle_id` ASC),
  CONSTRAINT `fk_Suiver_Persiode_Periode1`
    FOREIGN KEY (`Periode_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Periode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suiver_Persiode_Suiver1`
    FOREIGN KEY (`Suiver_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Suiver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suiver_Periode_Salle1`
    FOREIGN KEY (`Salle_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Salle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `brief-5-gestion-emploit-v2`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brief-5-gestion-emploit-v2`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brief-5-gestion-emploit-v2`.`User` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  `Ensegniant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Ensegniant_idx` (`Ensegniant_id` ASC),
  UNIQUE INDEX `Ensegniant_id_UNIQUE` (`Ensegniant_id` ASC),
  CONSTRAINT `fk_User_Ensegniant`
    FOREIGN KEY (`Ensegniant_id`)
    REFERENCES `brief-5-gestion-emploit-v2`.`Ensegniant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
